language: go
go:
  - 1.x

git:
  submodules: false # 不运行 git submodules 命令

before_install: # 安装 makefile 需要的一些包，其实也可以放在 install 阶段，看个人喜好
#- sudo apt-get update -qq
#- sudo apt-get install -qq -y make

install: true # 跳过 install 阶段，因为我已经定义了 before_install。其实 go 项目是需要安装依赖的，只是我放到了下面的 make mycli 命令中做

script: make test && make build # 先运行测试，然后编译

deploy:
  provider: releases
  api_key:
    secure: H4gKcKZutAqcBVsPfHg8ssL7rsBU1CgYSHXk0Btt58qnI8e8kwD6wbu0P7ZrGXGCciPU5f/IW6XXlkzuwQLjUiSuirQRVixxCJwH07LRY/xsY3vTs2rC5EW/mDVsmHq1liBaLarRddScAdsLq1z/ZTKxzYJcR2IpP/KtctV8oFGLwxBVgEW3wRFgIMMwROgooToUOvwW5OhBKl1sHCcSueWgLYrezs1CtWyNLngo2oxnFVF/vqCsKktKKhqP35MbEa2RNsdIGvSt24QFAQgyTJ4f+yJgUlWIl2V+zzmC4XKAcChcRo2UfWru8NJaP6UlEAo5jLgea9SVXhKadq8Dp3sq3KQbyO37o+D1ZMRUBDky5OOtOf5VFxE9btjdIvgfc0I+OgRwAKjVQHF5qITisuxhQBSO2zveamVAVNsq/hebQxpt6fIHI1lfrHXD0FmM/hHWrHsE88l+PD4E4KACswfjTAkjCCrKdt/OILRSlI83Sy8gaXj/o5gJAMw0/GlOl3b3zL/SP5c3spPtzH11BeM5doMX3elxNgJdvejFTU/7CkNGMun3GsRCTW2NlCScj+nW+NZz1lf88fMpTEVzvvaKYEwyePWxx+Ffrf0NyN4X71K/5GKq4v0nIr3ish2+ceaZNa8jvOB5kMfiw/pNwgLkEalTaxNDpTzLMWlGmnQ=
  file: learn-go
  skip_cleanup: true # 因为我要上传可执行文件到 release，所以不能自动把这个文件清除
  on:
    repo: yangchuang123456/learn-go
    branch: dev
    tags: true   #git tag 时发布
